name = "Hugo Zero"
license = "MIT"
licenselink = "https://github.com/TheYorkshireDev/hugo-zero/blob/master/LICENSE.md"
description = "Minimalistic Website Theme"
homepage = "https://github.com/TheYorkshireDev/hugo-zero"
tags = []
features = []
min_version = 0.17

[author]
  name = "Steven Cooney (TheYorkshireDev)"
  homepage = "https://github.com/TheYorkshireDev"

# Based Upon
[original]
  name = "Robin Wieruch"
  homepage = "https://github.com/rwieruch"
  repo = "https://github.com/rwieruch/hugo-minimal"
